spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://princess123.cb0kqmucctkl.ap-northeast-2.rds.amazonaws.com:3306/princess_db?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: admin
    password: princess123!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # JWT 설정 (JWTUtil에서 spring.jwt.* 형태로 참조)
  jwt:
    secret: mySecretKeyForDevelopment123456789
    expiration: 86400000

server:
  port: 8080
  forward-headers-strategy: framework

# JWT 설정 (기존 형태도 유지)
jwt:
  secret: mySecretKeyForDevelopment123456789
  expiration: 86400000

# AWS 설정 (환경변수 사용)
aws:
  access-key: ${AWS_ACCESS_KEY:your-access-key-here}
  secret-key: ${AWS_SECRET_KEY:your-secret-key-here}
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:princess-app-images}

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    server-url: https://princess-api.duckdns.org
  api-docs:
    path: /api-docs
    server-url: https://princess-api.duckdns.org
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    com.fwaiya.princess_backend: DEBUG